In [2]:
import random
import matplotlib.pyplot as plt
import numpy as np

In [26]:
# Cái này đéo có tác dụng gì
X0 = np.array([0.25,0.2,0.55])
P = np.array([[0.7,0.1,0.2],
             [0.2,0.8,0.2],
             [0.1,0.1,0.6]]) 
for i in range(3):
    X0 = np.dot(P,X0)
X0


array([0.32105, 0.4352 , 0.24375])

In [29]:
# tính câu 2a
X0 = np.array([1,0,0,0])
P = np.array([[0.5,0.25,0,0],
             [0.5,0.25,1/3,1/3],
             [0,0.25,1/3,1/3],
             [0,0.25,1/3,1/3]])
for i in range(5):
    X0 = np.dot(P,X0)
X0

array([0.20334201, 0.34280961, 0.22692419, 0.22692419])

In [3]:
# giả lập câu 2
def move(cur_pos):
    p = np.random.uniform(0,1)
    if(cur_pos == 1):
        if(p < 0.5):
            return 1
        else:
            return 2
    elif(cur_pos == 2):
        if(p < 0.25):
            return 1
        elif(p < 0.5):
            return 2
        elif(p < 0.75):
            return 3
        else:
            return 4
    elif(cur_pos == 3):
        if(p < 1/3):
            return 2
        elif(p < 2/3):
            return 3
        else:
            return 4
    else:
        if(p < 1/3):
            return 2
        elif(p < 2/3):
            return 3
        else:
            return 4

In [9]:
# Câu 2a
def tan_xuat2AB(moves,N):
    last_pos = []
    for i in range(N):
        cur_pos = 1
        for j in range(moves):
            cur_pos = move(cur_pos)
        last_pos.append(cur_pos)
        
    y = np.bincount(last_pos)
    ii = np.nonzero(y)[0]
    freq = np.vstack((ii,y[ii])).T
    freq = freq.astype('float64')
    
    for i in range(np.shape(freq)[0]):
        freq[i][1] = freq[i][1] / N
    return freq

tan_xuat2AB(5,10000)

array([[1.    , 0.1667],
       [2.    , 0.3364],
       [3.    , 0.2525],
       [4.    , 0.2444]])

In [ ]:
# Câu 2b
tan_xuat2AB(5,10000)

In [6]:
# Câu 2c
def new_move(cur_pos):
    p = np.random.uniform(0,1)
    if(cur_pos == 1):
        return 2
    elif(cur_pos == 2):
        if(p < 1/3):
            return 1
        elif(p < 2/3):
            return 3
        else:
            return 4
    elif(cur_pos == 3):
        if(p < 1/2):
            return 2
        else:
            return 4
    else:
        if(p < 1/2):
            return 2
        else:
            return 3

def tan_xuat2C(moves,N):
    last_pos = []
    list_pos = []
    for i in range(N):
        cur_pos = 1
        repeat = 1
        past_pos = 1
        list_temp = []
        for j in range(moves):
            cur_pos = move(cur_pos)
            list_temp.append(cur_pos)
            if(cur_pos == past_pos):
                repeat += 1
            else:
                repeat = 0
            past_pos = cur_pos
            
            if(repeat == 3):
                repeat = 0
                j += 1
                cur_pos = new_move(cur_pos)
                list_temp.append(cur_pos)
        last_pos.append(cur_pos)
        list_pos.append(list_temp)
        
    #print(list_pos)
    y = np.bincount(last_pos)
    ii = np.nonzero(y)[0]
    freq = np.vstack((ii,y[ii])).T
    freq = freq.astype('float64')
    
    for i in range(np.shape(freq)[0]):
        freq[i][1] = freq[i][1] / N
    return freq

tan_xuat2C(100,10000)

array([[1.    , 0.152 ],
       [2.    , 0.3411],
       [3.    , 0.2537],
       [4.    , 0.2532]])

In [8]:
# Câu 3
def len_xe():
    p = np.random.uniform(0,1)
    if(p < 0.5):
        return 0
    elif(p < 0.9):
        return 1
    else:
        return 2

def xuong_xe():
    p = np.random.uniform(0,1)
    if(p < 0.2):
        return 0
    else:
        return 1

In [10]:
# Câu 3a
def tan_xuat_3A(N):
    f_ans = []
    for i in range(N):
        khach_len_xe = 0
        for j in range(2):
            khach_len_xe += len_xe()
        if(khach_len_xe == 0):
            f_ans.append(1)
        else:
            f_ans.append(0)
    return sum(f_ans)/N

tan_xuat_3A(100000)

0.249795

In [11]:
# Cau 3b
def tan_xuat_3B(N):
    f_ans = []
    for i in range(N):
        khach_len_xe = 0
        for j in range(3):
            khach_len_xe += len_xe()
        if(khach_len_xe == 0):
            f_ans.append(1)
        else:
            f_ans.append(0)
    return sum(f_ans)/N

tan_xuat_3B(100000)

0.12573

In [12]:
# Cau 3c
def tan_xuat_3C(N):
    f_ans = []
    for i in range(N):
        khach_len_xe = 0
        for j in range(5):
            khach_len_xe += len_xe()
        if(khach_len_xe >= 5):
            f_ans.append(1)
        else:
            f_ans.append(0)
    return sum(f_ans)/N

tan_xuat_3C(100000)

0.156

In [ ]:
# Câu 3d

In [25]:
# Câu 3e
# Đéo biết đúng ko
def tan_xuat_3E(N):
    E_ans = []
    for i in range(N):
        khach_tren_xe = 0
        for j in range(2):
            khach_tren_xe += len_xe()
            for k in range(khach_tren_xe):
                khach_tren_xe -= xuong_xe()
        E_ans.append(khach_tren_xe)
    #print(E_ans)
    return sum(E_ans)/N

tan_xuat_3E(100000)

0.14314

In [24]:
# Câu 3f
# Đéo biết đúng ko
def tan_xuat_3F(N):
    E_ans = []
    for i in range(N):
        khach_tren_xe = 0
        for j in range(3):
            khach_tren_xe += len_xe()
            for k in range(khach_tren_xe):
                khach_tren_xe -= xuong_xe()
        E_ans.append(khach_tren_xe)
    #print(E_ans)
    return sum(E_ans)/N

tan_xuat_3F(100000)

0.14974