In [2]:
#Thông tin sinh viên
#   Họ và tên: Phan Trí Tài
#   MSSV: 20127318

In [5]:
#Câu 1
import numpy as np

def diagonalize_matrix(A):
    # Kiểm tra xem A có phải là ma trận vuông không
    if A.shape[0] != A.shape[1]:
        return "Lỗi: Ma trận A phải là ma trận vuông."

    # Tính các riêng trị và riêng vector
    eigenvalues, eigenvectors = np.linalg.eig(A)
    
    # Sắp xếp theo thứ tự giảm dần của riêng trị
    idx = eigenvalues.argsort()[::-1]   
    eigenvalues = eigenvalues[idx]
    eigenvectors = eigenvectors[:,idx]

    # Ma trận P bao gồm các riêng vector
    P = eigenvectors

    # Ma trận đường chéo D bao gồm các riêng trị trên đường chéo
    D = np.diag(eigenvalues)

    # Tính P^(-1)
    P_inv = np.linalg.inv(P)

    return P, D, P_inv

# Test the function
A = np.array([[2, 1], [1, 2]])  # this is your matrix
P, D, P_inv = diagonalize_matrix(A)
print("P:\n", P)
print("D:\n", D)
print("P^(-1):\n", P_inv)


P:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
D:
 [[3. 0.]
 [0. 1.]]
P^(-1):
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [6]:
#Câu 2a
#Thư viện scipy.linalg cũng cung cấp các hàm để tính toán riêng trị và riêng vector, và nó cũng cung cấp một hàm inv() để tính ma trận nghịch đảo.
from scipy import linalg

# Tính riêng trị và riêng vector
eigvals, eigvecs = linalg.eig(A)

# Ma trận P
P = eigvecs

# Ma trận đường chéo D
D = np.diag(eigvals)

# Ma trận P^(-1)
P_inv = linalg.inv(P)

In [7]:
#Câu 2b
#Chéo hóa ma trận có nhiều ứng dụng trong lý thuyết ma trận và trong các ứng dụng thực tế. Một số ứng dụng cụ thể bao gồm:

# - Giải phương trình vi phân và hệ phương trình vi phân: Việc chéo hóa ma trận cho phép giải các phương trình vi phân tuyến tính và hệ phương trình vi phân tuyến tính với hệ số hằng số một cách dễ dàng hơn.

# - Tính toán lũy thừa của ma trận: Khi một ma trận được chéo hóa, việc tính toán lũy thừa của ma trận trở nên đơn giản hơn nhiều. Nếu A = PDP^(-1), thì A^n = PD^nP^(-1), trong đó D^n là ma trận đường chéo với các phần tử trên đường chéo là lũy thừa của các riêng trị tương ứng.

# - Ứng dụng trong phân tích hệ thống và điều khiển: Trong lý thuyết hệ thống và điều khiển, việc chéo hóa ma trận cho phép dễ dàng phân tích và điều khiển hệ thống.

# - Ứng dụng trong phân tích phổ (spectral analysis): Chéo hóa ma trận cho phép tách phần tử riêng, làm cho việc phân tích phổ trở nên dễ dàng hơn.

# - Ứng dụng trong vật lý lượng tử: Trong lý thuyết vật lý lượng tử, chéo hóa ma trận cho phép giải các phương trình Schrödinger dễ dàng hơn.